name: Update Connector Actions CSVs
on:
  push:
    branches:
      - main
    paths:
      - '**.ssp'
      - '**/manifest.json'

jobs:
  get-used-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Write actions to csv
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.ssp$'); do
            python get_actions_from_ssp.py -i "$file" -o "${file%.ssp}.csv"
          done

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Action"
          git add -A
          git commit -m "Automatically updated CSVs with connectors/actions" || echo "No changes to commit"
          git push
