name: Update version
on: 
  push:
    branches:
      - main    
      - branchtest
    paths:
      - '**.ssp'
      - '**/manifest.json'
      - '**/logo.png'
      - '**/logo.jpeg'
      - '**/logo.jpg'     

permissions:
  contents: write # for checkout & releases
  pull-requests: write # for comments
  packages: write # for publish

env:
  MARKETPLACE_URL: "https://marketplace.swimlane.com" 
  SCRIPT_LOCATION: ".github/workflows/scripts"
  MARKETPLACE_USERNAME: "swimlane"
  MARKETPLACE_PASSWORD: "f3Juc5p#QWd2$@kzuM"

jobs:
  version-the-ssp:
    runs-on: ubuntu-latest
    steps:
      # checkout 
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # prerequisites
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install jq
        run: sudo apt install -y imagemagick jq

      - name: Install requests
        run: pip3 install -r requirements.txt          

      # publish
      - name: Publish to Marketplace
        run: |
          original_ifs="$IFS"
          IFS=$'\n'
          changed_files=$(git diff --name-only HEAD~1 HEAD)
          echo "hello"

          for file in $changed_files; do
              if [[ "$file" == *.ssp ]]; then
                  folder=$(dirname $file)
                  echo "$folder"
                  echo "$pwd"
                  repo_dir="$(pwd)/$folder"
                  echo "$repo_dir""
                  python ${{ env.SCRIPT_LOCATION }}/publish.py --repo-dir "$repo_dir" --publish --publish_url '${{ env.MARKETPLACE_URL }}'  --username '${{ env.MARKETPLACE_USERNAME }}' --password '${{ env.MARKETPLACE_PASSWORD }}'
                  fi
          done          
          IFS="$original_ifs"

      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "Versioned Bundle" || echo "No changes to commit"
          git push
